inference:
  _target_: src.datasets.TTSDataset
  data_dir_path: ${inferencer.data_dir_path}
  text_from_cli: ${inferencer.text_from_cli}
  is_train: False
  instance_transforms: ${transforms.instance_transforms.inference}
