train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.MOSMetric
    name: "MOS" # it is better to avoid spaces in names
