_target_: src.model.hifi_gan.HiFiGAN
generator_config: {
        "n_mels": 80,
        "hidden_dim": 512,
        "k_u": [16, 16, 4, 4],
        "k_r": [3, 7, 11],
        "D_r": [[[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]], [[1, 1], [3, 1], [5, 1]]]
      }
mpd_periods: [2, 3, 5, 7, 11]
