train:
    _target_: torch.utils.data.DataLoader
    batch_size: 64
    num_workers: 4
    pin_memory: True

val:
    _target_: torch.utils.data.DataLoader
    batch_size: 1
    num_workers: 1
    pin_memory: True
